;
CREATE CACHED TABLE ADDRESS.ADDRESS(
    ADDRESS_ID VARCHAR(255) NOT NULL,
    PERSON_ID VARCHAR(255) NOT NULL,
    STREET_AND_NUMBER VARCHAR(255),
    ZIP_CODE VARCHAR(255)
);
ALTER TABLE ADDRESS.ADDRESS ADD CONSTRAINT ADDRESS.CONSTRAINT_E PRIMARY KEY(ADDRESS_ID);
