;              
CREATE USER IF NOT EXISTS SA SALT 'fac451cb9e6ab79a' HASH '42a34a688d203875e02fd39a5451522961472da63791fa758d5c3a1abb879084' ADMIN;            
CREATE SCHEMA IF NOT EXISTS PROJECTION AUTHORIZATION SA;       
CREATE SCHEMA IF NOT EXISTS PERSON AUTHORIZATION SA;           
CREATE SCHEMA IF NOT EXISTS ADDRESS AUTHORIZATION SA;          
CREATE SCHEMA IF NOT EXISTS SAGA AUTHORIZATION SA;             
CREATE SEQUENCE SAGA.HIBERNATE_SEQUENCE START WITH 1;
CREATE CACHED TABLE PERSON.PERSON(
    ID VARCHAR(255) NOT NULL,
    ADDRESS_ID VARCHAR(255),
    FULL_NAME VARCHAR(255)
);    
ALTER TABLE PERSON.PERSON ADD CONSTRAINT PERSON.CONSTRAINT_8 PRIMARY KEY(ID);  
-- 0 +/- SELECT COUNT(*) FROM PERSON.PERSON;   
CREATE CACHED TABLE SAGA.ASSOCIATION_VALUE_ENTRY(
    ID BIGINT NOT NULL,
    ASSOCIATION_KEY VARCHAR(255) NOT NULL,
    ASSOCIATION_VALUE VARCHAR(255),
    SAGA_ID VARCHAR(255) NOT NULL,
    SAGA_TYPE VARCHAR(255)
);      
ALTER TABLE SAGA.ASSOCIATION_VALUE_ENTRY ADD CONSTRAINT SAGA.CONSTRAINT_B PRIMARY KEY(ID);     
-- 0 +/- SELECT COUNT(*) FROM SAGA.ASSOCIATION_VALUE_ENTRY;    
CREATE INDEX SAGA.IDXK45EQNXKGD8HPDN6XIXN8SGFT ON SAGA.ASSOCIATION_VALUE_ENTRY(SAGA_TYPE, ASSOCIATION_KEY, ASSOCIATION_VALUE); 
CREATE INDEX SAGA.IDXGV5K1V2MH6FRXUY5C0HGBAU94 ON SAGA.ASSOCIATION_VALUE_ENTRY(SAGA_ID, SAGA_TYPE);            
CREATE CACHED TABLE SAGA.SAGA_ENTRY(
    SAGA_ID VARCHAR(255) NOT NULL,
    REVISION VARCHAR(255),
    SAGA_TYPE VARCHAR(255),
    SERIALIZED_SAGA BLOB
);     
ALTER TABLE SAGA.SAGA_ENTRY ADD CONSTRAINT SAGA.CONSTRAINT_BD PRIMARY KEY(SAGA_ID);            
-- 0 +/- SELECT COUNT(*) FROM SAGA.SAGA_ENTRY; 
CREATE CACHED TABLE PROJECTION.PERSON_SUMMARY(
    PERSON_ID VARCHAR(255) NOT NULL,
    ADDRESS_ID VARCHAR(255),
    FULL_NAME VARCHAR(255),
    STREET_AND_NUMBER VARCHAR(255),
    ZIP_CODE VARCHAR(255)
);  
ALTER TABLE PROJECTION.PERSON_SUMMARY ADD CONSTRAINT PROJECTION.CONSTRAINT_7 PRIMARY KEY(PERSON_ID);           
-- 0 +/- SELECT COUNT(*) FROM PROJECTION.PERSON_SUMMARY;       
CREATE CACHED TABLE ADDRESS.ADDRESS(
    ADDRESS_ID VARCHAR(255) NOT NULL,
    PERSON_ID VARCHAR(255),
    STREET_AND_NUMBER VARCHAR(255),
    ZIP_CODE VARCHAR(255)
);
ALTER TABLE ADDRESS.ADDRESS ADD CONSTRAINT ADDRESS.CONSTRAINT_E PRIMARY KEY(ADDRESS_ID);
-- 0 +/- SELECT COUNT(*) FROM ADDRESS.ADDRESS;
