;              
CREATE CACHED TABLE PERSON.PERSON(
    ID VARCHAR(255) NOT NULL,
    ADDRESS_ID VARCHAR(255),
    FULL_NAME VARCHAR(255)
);    
ALTER TABLE PERSON.PERSON ADD CONSTRAINT PERSON.CONSTRAINT_8 PRIMARY KEY(ID);  

